# Generated by Django 4.1.7 on 2023-04-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CarDealer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=10)),
                ("phone", models.PositiveBigIntegerField(max_length=10)),
                ("earnings", models.IntegerField(default=0)),
                ("type", models.CharField(blank=True, max_length=20)),
                ("password", models.CharField(max_length=50)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.location"
                    ),
                ),
            ],
        ),
    ]
