# Generated by Django 4.1.7 on 2023-04-06 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_cardealer_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardealer",
            old_name="type",
            new_name="types",
        ),
    ]
