# Generated by Django 4.1.7 on 2023-04-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_rename_type_cardealer_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="")),
                ("capacity", models.CharField(max_length=2)),
                ("is_available", models.BooleanField(default=True)),
                ("rent", models.CharField(blank=True, max_length=10)),
                (
                    "car_dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app1.cardealer"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app1.location",
                    ),
                ),
            ],
        ),
    ]
