# Generated by Django 4.1.7 on 2023-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_alter_car_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=10)),
                ("phone", models.PositiveBigIntegerField(max_length=10)),
                ("location", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
