# Generated by Django 4.1.7 on 2023-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
