# Generated by Django 4.1.7 on 2023-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_order_paid_order_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
