# Generated by Django 4.1.7 on 2023-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_order_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
